version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env 
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://user:password@db/fileexchange
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=cloud.comp-project

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=fileexchange
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password

volumes:
  mysql_data:
